[package]
name = "blackjack_ui"
description = "A procedural, node-based modelling tool, made in Rust"
homepage = "https://github.com/setzer22/blackjack"
repository = "https://github.com/setzer22/blackjack"
license = "MIT"
version = "0.1.0"
keywords = ["gamedev", "3d", "modelling", "procedural"]
authors = ["setzer22"]
edition = "2021"

[features]
tracy = ["profiling/profile-with-tracy"]

[dependencies]
# Workspace dependencies
blackjack_commons = { path = "../blackjack_commons" }
blackjack_engine = { path = "../blackjack_engine" }

# Forked crates
egui-winit = { version = "0.18" } # This is a patch.crates-io fork on main Cargo.toml
egui-wgpu = { version = "0.18" } # This is a patch.crates-io fork on main Cargo.toml
egui = { version = "0.18", features = ["persistence"] } # This is a patch.crates-io fork on main Cargo.toml

# Git dependencies
egui_node_graph = { git = "https://github.com/setzer22/egui_node_graph", rev = "54ae2dc45fb8882563ca98e2b8910af1ea1413dd", features = [
    "persistence",
] }
rend3 = { git = "https://github.com/Cakefish/rend3.git", rev = "1b6cac44938c0890" }
rend3-routine = { git = "https://github.com/Cakefish/rend3.git", rev = "1b6cac44938c0890" }
glsl-include = { git = "https://github.com/setzer22/glsl-include", rev = "d9b1ade" }

# Crates.io crates
glam = { version = "0.20", features = ["serde", "bytemuck"] }
env_logger = { version = "0.9", default-features = false, features = [
    "termcolor",
    "atty",
] }
winit = { version = "0.26" }
wgpu = "0.12"
pollster = "0.2"
smallvec = { version = "1.7.0", features = ["serde"] }
itertools = "0.10"
anyhow = { version = "1.0", features = ["backtrace"] }
bytemuck = { version = "1.7", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
ron = "0.7"
rfd = { version = "0.9.1", default-features = false, features = ["xdg-portal"] }
float-ord = "0.3.2"
spin_sleep = "1.0.0"
rayon = "1.5.1"
nonmax = "0.5"
slotmap = { version = "1.0", features = ["serde"] }
num-traits = "0.2.14"
atomic_float = "0.1"
profiling = { version = "1.0" }
image = { version = "0.24", default-features = false, features = ["png"] }
nom = "7.1"
mlua = { version = "0.8.1", features = ["luau"] }
notify = "4.0"
walkdir = "2"
syntect = "4.6"
bimap = "0.6.2"
dyn-clone = "1.0"
noise = "0.7"
rstar = "0.9.3"
wavefront_rs = "1.0.4"
derive_more = "0.99"
